# Generated by Django 3.0 on 2020-01-29 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='sender_name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='sender_username',
        ),
        migrations.AddField(
            model_name='question',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_name',
            field=models.TextField(default='', verbose_name='telegram name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.TextField(null=True, verbose_name='telegram username'),
        ),
    ]
